---
title: "umass_verification_pipeline"
output: html_document
date: "2022-12-12"
---


```{r library, include=FALSE}
library(readxl)
library(readr)
library(knitr)
library(kableExtra)
library(stringr)
library(dplyr)
library(tidyr)
library(janitor)
library(flextable)
library(data.table)
library(lubridate)
library(forcats)
library(data.table)
library(forcats)
library(ggplot2)
library(tidyverse)
library(glue)
library(googledrive)
library(readr)
#drive_auth()
```

# DATA GENERATOR

```{r}
residential_data <-  read_excel( "residential_dashboard_data.xlsx")

dim(residential_data)

```

```{r}

unemployment_list <- c('Dont Know', 'Government assistant programme', 'None')
```


```{r}
sumary_df <- residential_data %>% 
  group_by(`Local Community Development Area`) %>% 
  summarise(median_household_income = median(total_monthly_income, na.rm = TRUE),
            Employment_rate = sum(!(`Primary source of income of the household?` %in% unemployment_list)) / n() * 100,
            Industrial_activity = sum(`Do you have a business you run in your household?` == TRUE) / n() * 100,
            Gen_expenditure = median(total_monthly_gen_spend, na.rm = TRUE),
            Energy_spend_ratio = (( sum(total_monthly_gen_spend, na.rm = TRUE) + sum(monthly_grid_spend, na.rm = TRUE)) / sum(total_monthly_income, na.rm = TRUE)) * 100,
            )
```

```{r}
energy_income_ratio <- residential_data %>% 
  group_by(`Local Community Development Area`) %>% 
  summarise(Energy_spend_ratio = (( sum(total_monthly_gen_spend, na.rm = TRUE) + sum(monthly_grid_spend, na.rm = TRUE)) / sum(total_monthly_income, na.rm = TRUE)) * 100)
```





```{r}
sumary_df
```


